package controller.employer;

import javafx.fxml.FXML;

import java.io.IOException;

import com.jfoenix.controls.JFXButton;

import controller.Controller;
import dataAccess.sql.JobsDAO_Sql;
import javafx.event.ActionEvent;

import javafx.scene.control.Label;
import model.account.EmployeeAccount;
import model.event.WorkEvent;
/**
 * AddPendingResignationController controls  PendingResignation
 * for different resignations requested by the employee
 *
 * @version b.2.2
 * @since b.2.2
 * @author Low Qing Ning
 */
public class AddPendingResignationController extends Controller {
	@FXML
	private Label lbJobName;
	@FXML
	private Label lbResignationName;
	@FXML
	private Label lbReasonsToResign;
	@FXML
	private JFXButton Approvebtn;
	@FXML
	private JFXButton Declinebtn;
	private EmployeeAccount acc;
	private WorkEvent w;
	JobsDAO_Sql jobDAO =new JobsDAO_Sql();
	// Event Listener on JFXButton[#Approvebtn].onAction
	@FXML
	public void handleApproveBtn(ActionEvent event) {
		// TODO Autogenerated
		jobDAO.acceptResignation(acc.getLoginEmail(), w.getJobTitle());
		try {
			m.swapScene("/employer/PendingResignation.fxml");
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}
	// Event Listener on JFXButton[#Declinebtn].onAction
	@FXML
	public void handleDeclineBtn(ActionEvent event) {
		
		// TODO Autogenerated
		jobDAO.transferFromPendingResignToAccepted(acc.getLoginEmail(), w.getJobTitle());
		try {
			m.swapScene("/employer/PendingResignation.fxml");
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		
	}
	public void setPendingDetails(WorkEvent w, EmployeeAccount acc) {
		// TODO Auto-generated method stub
		this.w = w;
		this.acc = acc;
		lbJobName.setText(w.getJobTitle());
		lbResignationName.setText(acc.getName());
		lbReasonsToResign.setText(acc.getAboutMe());
	}
}
