package controller.employer;

import java.awt.image.BufferedImage;
import java.io.IOException;

import com.jfoenix.controls.JFXButton;
import com.jfoenix.controls.JFXPopup;

import controller.Controller;
import dataAccess.ImageUpload;
import dataAccess.sql.AccountDAO_Sql;
import javafx.embed.swing.SwingFXUtils;
import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.scene.control.Label;
import javafx.scene.image.ImageView;

public class EmployerdrawerController extends Controller {
	@FXML
	private ImageView accountPicture;
	@FXML
	private Label name;
	@FXML
	private Label email;
	@FXML
	private JFXButton jobsButton;
	@FXML
	private JFXButton profileButton;
	@FXML
	private JFXButton feedbackButton;
	@FXML
	private JFXButton logoutButton;
	@FXML
	private JFXPopup popup;
	@FXML
	private JFXButton homeButton;

	public void initialize() {
		name.setText(s.getAcc().getName());
		email.setText(s.getAcc().getLoginEmail());
		jobsButton.setText("CREATE JOB");
		BufferedImage img = new AccountDAO_Sql().getProfilePic(s.getAcc().getLoginEmail());
		img = (img == null)? ImageUpload.defaultProfilePic() : img;
		accountPicture.setImage(SwingFXUtils.toFXImage(img, null));
	}
	// Event Listener on JFXButton[#jobsButton].onAction
	@FXML
	public void handleJobs(ActionEvent event) {

		try {
			m.swapScene("/employer/CreateJob.fxml");
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		
	}

	// Event Listener on JFXButton[#profileButton].onAction
	@FXML
	public void handleProfile(ActionEvent event) {
		// TODO Autogenerated
		try {
			m.swapScene("/employer/Profile.fxml");
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}
	// Event Listener on JFXButton[#feedbackButton].onAction
	@FXML
	public void handleFeedback(ActionEvent event) {
		// TODO Autogenerated
		try {
			m.swapScene("/employer/Feedback.fxml");
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}
	// Event Listener on JFXButton[#logoutButton].onAction
	@FXML
	public void handleLogout(ActionEvent event) {
		try {
			m.swapScene("/EmployeeOrEmployer.fxml");
			s.setAcc(null);
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}
	
	@FXML public void handleStatistics(ActionEvent event) {
		try {
			m.swapScene("/employer/StatisticsPie.fxml");
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}
	@FXML public void handleHome(ActionEvent event) {
		try {
			m.swapScene("/employer/Home.fxml");
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}
	
}
