package controller.employer;

import java.io.IOException;
import java.net.URL;
import java.util.ArrayList;
import java.util.ResourceBundle;

import com.jfoenix.controls.JFXButton;
import com.jfoenix.controls.JFXDrawer;
import com.jfoenix.controls.JFXHamburger;

import controller.Controller;
import dataAccess.sql.JobsDAO_Sql;
import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.fxml.Initializable;
import javafx.scene.control.ScrollPane;
import javafx.scene.input.MouseEvent;
import javafx.scene.layout.VBox;
import model.account.EmployerAccount;
import model.event.WorkEvent;

/**
 * EmployerHomeController controls the EmployerHome and appends the JobDetails
 * for different job created by the employer
 *
 * @version b.2.2
 * @since a.1
 * @author Low Qing Ning
 */
public class HomeController extends Controller implements Initializable {
	 @FXML
	    private JFXHamburger fxHamburg;

	    @FXML
	    private ScrollPane ScrollPaneEmployerHome;

	    @FXML
	    private VBox VBoxCurrent;

	    @FXML
	    private JFXButton btnPendingApplicant;

	    @FXML
	    private JFXButton btnPendingResignation;

	    @FXML
	    private JFXDrawer fxDrawer;

	/**
	 * Event Listener on JFXButton[#btnPendingApplicant].onAction 
	 * 
	 * 
	 * @param event
	 */
    @FXML
    void handlePendingApplicant(ActionEvent event) {
    	try {
			m.swapScene("/employer/ApplicantPage.fxml");

		} catch (IOException e) {
			e.printStackTrace();
		}
    }
    /**
	 * Event Listener on JFXButton[#btnPending].onAction 
	 * 
	 * 
	 * @param event
	 */
    @FXML
    void handlePendingResignation(ActionEvent event) {
    	try {
			m.swapScene("/employer/PendingResignation.fxml");

		} catch (IOException e) {
			e.printStackTrace();
		}
    }
	/**
	 * Event Listener on JFXButton[#btnHome].onAction ALL got Runtime Error <--
	 * This still a problem? If not remove -JK
	 * 
	 * @param event
	 */
	@FXML
	public void handleHome(ActionEvent event) {
		try {
			m.swapScene("/employer/Home.fxml");

		} catch (IOException e) {
			e.printStackTrace();
		}
	}
	/**
	 * Event Listener on JFXButton[#btnJobs].onAction
	 * 
	 * @param event
	 */
    @FXML
    void handleJobs(ActionEvent event) {
    	try {
			m.swapScene("/employer/CreateJob.fxml");

		} catch (IOException e) {
			e.printStackTrace();
		}
    }


	// Event Listener on JFXButton[#btnProfile].onAction
	@FXML
	public void handleProfile(ActionEvent event) {
		try {
			m.swapScene("/employer/Profile.fxml");

		} catch (IOException e) {
			e.printStackTrace();
		}
	}

	// Event Listener on JFXButton[#btnFeedback].onAction
	@FXML
	public void handleFeedBack(ActionEvent event) {
		try {
			m.swapScene("/employer/Feedback.fxml");

		} catch (IOException e) {
			e.printStackTrace();
		}
	}

	// Event Listener on JFXButton[#btnLogout].onAction
	@FXML
	public void handleLogout(ActionEvent event) {
		// TODO Autogenerated
		try {
			m.swapScene("/EmployeeOrEmployer.fxml");
			s.setAcc(null);
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}

	// Event Listener on TextField[#fieldSearchBox].onAction
	@FXML
	public void handleSearchBox(ActionEvent event) {
		// TODO Autogenerated
		
	}

	 @FXML
	 void handleStatistics(ActionEvent event) {
		 try {
				m.swapScene("/employer/StatisticsPie.fxml");
				
			} catch (IOException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
	    }
	@Override
	public void initialize(URL arg0, ResourceBundle arg1) {
		// TODO Auto-generated method stub
		EmployerAccount acc = (EmployerAccount)s.getAcc();
		//System.out.println(acc);
//		lbName.setText(acc.getCompanyName());
//		lbEmail.setText(acc.getLoginEmail());
		
		JobsDAO_Sql data = new JobsDAO_Sql();
		ArrayList<WorkEvent> workArr = new ArrayList<WorkEvent>();
//		System.out.println(s.getAcc().getLoginEmail());
		workArr = data.getJobOfEmployer(s.getAcc().getLoginEmail());
		System.out.println(workArr);
//		workArr = data.getEmployerJob("");

		System.out.println(workArr);
		if (workArr != null ){
			
		for(int i=0 ; i<workArr.size() ; i++){
				try {
					FXMLLoader loader = m.getScene("/employer/JobDetailsPage.fxml");
					VBoxCurrent.getChildren().add(loader.load());
					((JobDetailsPageController)loader.getController()).setJobDetails(workArr.get(i));
				} catch (IOException e) {
					e.printStackTrace();
				}
			}
		
		}
		
		/* Drawer */
		try {
			VBox box = m.getScene("/employer/Employerdrawer.fxml").load();
			fxDrawer.setSidePane(box);
			fxHamburg.addEventHandler(MouseEvent.MOUSE_CLICKED, (e) -> {

				if (fxDrawer.isShown()) {
					fxDrawer.close();
				} else {
					fxDrawer.open();
				}
			});
		} catch (IOException e1) {
			// TODO Auto-generated catch block
			e1.printStackTrace();
		}
		// end of drawer
	}

		
}
