package controller.employer;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.fxml.Initializable;

import java.io.IOException;
import java.net.URL;
import java.util.ArrayList;
import java.util.ResourceBundle;

import com.jfoenix.controls.JFXButton;

import controller.Controller;
import dataAccess.sql.JobsDAO_Sql;
import javafx.event.ActionEvent;

import javafx.scene.control.Label;

import javafx.scene.control.ScrollPane;

import javafx.scene.layout.VBox;
import model.account.EmployeeAccount;
import model.event.WorkEvent;
/**
 * PendingResignationController controls the PendingResignation and appends the AddPendingResignation
 * for different resignations by the employee
 *
 * @version b.2.2
 * @since b.2.2
 * @author Low Qing Ning
 */
public class PendingResignationController extends Controller implements Initializable{
	@FXML
	private JFXButton Homebtn;
	@FXML
	private Label lbJob;
	@FXML
	private JFXButton lbBack;
	@FXML
	private Label lbPendingResignation;
	@FXML
	private ScrollPane ScrollPaneApplicationPage;
	@FXML
	private VBox VBoxApplication;

	// Event Listener on JFXButton[#Homebtn].onAction
	@FXML
	public void handleBack(ActionEvent event) {
		// TODO Autogenerated
		try {
			m.swapScene("/employer/Home.fxml");
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}

	@Override
	public void initialize(URL arg0, ResourceBundle arg1) {
		// TODO Auto-generated method stub
		JobsDAO_Sql jobDAO = new JobsDAO_Sql();

		ArrayList<WorkEvent> workList = jobDAO.getJobOfEmployer(s.getAcc().getLoginEmail());

		if(workList != null){
			for(WorkEvent w : workList){
				ArrayList<EmployeeAccount> employeeList = jobDAO.getPendingOfResignation(w.getJobTitle());
				for (EmployeeAccount acc : employeeList) {
					try {
						FXMLLoader loader = m.getScene("/employer/AddPendingResignation.fxml");
						
						VBoxApplication.getChildren().add(loader.load());
						
						AddPendingResignationController c = (AddPendingResignationController) loader.getController();
						c.setPendingDetails(w, acc);
					} catch (IOException e) {
						// TODO Auto-generated catch block
						e.printStackTrace();
					}
					
				}
			}
		}
	}
}
