package controller.employee;

import java.io.IOException;
import java.util.ArrayList;

import com.jfoenix.controls.JFXButton;
import com.jfoenix.controls.JFXDrawer;
import com.jfoenix.controls.JFXHamburger;

import controller.Controller;
import dataAccess.AccountDAO;
import dataAccess.sql.JobsDAO_Sql;
import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.control.ScrollPane;
import javafx.scene.control.TextField;
import javafx.scene.input.MouseEvent;
import javafx.scene.layout.VBox;
import model.event.WorkEvent;

/**
 * 
 * Used in EmployeeHistoryCurrentPane.fxml
 * 
 * @version a.3
 * @since a
 * @author NigelChen
 *
 */
public class HistoryCurrentController extends Controller {
	@FXML
	private JFXButton btnJobs;
	@FXML
	private JFXButton btnHistory;
	@FXML
	private JFXButton btnProfile;
	@FXML
	private JFXButton btnFeedback;
	@FXML
	private TextField fieldSearchBox;
	@FXML
	private ScrollPane ScrollPaneCurrent;
	@FXML
	private VBox VBox;
	@FXML
    private JFXHamburger fxHamburg;
	@FXML
    private JFXDrawer fxDrawer;
	@FXML
	private JFXButton btnCurrent;
	@FXML
	private JFXButton btnPending;
	@FXML
	private JFXButton btnHome;
	@FXML
	private JFXButton btnLogout;
	
	private ArrayList<WorkEvent> workList = new JobsDAO_Sql().getAcceptedOfEmployee(s.getAcc().getLoginEmail());
	// Event Listener on TextField[#fieldSearchBox].onAction
	@FXML
	public void handleSearchBox(ActionEvent event) {
		// TODO Autogenerated
	}

	// Event Listener on JFXButton[#btnCurrent].onAction
	@FXML
	public void handleCurrent(ActionEvent event) {
		// TODO Autogenerated
	}

	// Event Listener on JFXButton[#btnPending].onAction
	@FXML
	public void handlePending(ActionEvent event) {
		try {
			m.swapScene("/employee/historyPending.fxml");
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}

	/**
	 * Generate a pane from EmployeeHistoryCurrentPane.fxml and append
	 * accordingly.
	 */
	public void initialize() {

		for(WorkEvent w : workList){
			try {
				System.out.println("abc");
				FXMLLoader loader = m.getScene("/employee/HistoryCurrentPane.fxml");
				VBox.getChildren().add(loader.load());
				HistoryCurrentPaneController c = (HistoryCurrentPaneController) loader.getController();
				c.setWorkDetails(w, new JobsDAO_Sql().getEmployerOfJob(w.getJobTitle()));
			} catch (IOException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
		}
		
		
		try {
			VBox box = m.getScene("/Drawer.fxml").load();
			fxDrawer.setSidePane(box);
			fxHamburg.addEventHandler(MouseEvent.MOUSE_CLICKED, (e) -> {
				

				if (fxDrawer.isShown()) {
					fxDrawer.close();
				} else {
					fxDrawer.open();
				}
			});
		} catch (IOException e1) {
			// TODO Auto-generated catch block
			e1.printStackTrace();
		}
		

	}
}
