package controller.employee;

import java.io.IOException;

import com.jfoenix.controls.JFXButton;
import com.jfoenix.controls.JFXDialog;
import com.jfoenix.controls.JFXDialogLayout;
import com.jfoenix.controls.JFXSnackbar;

import controller.Controller;
import dataAccess.sql.JobsDAO_Sql;
import javafx.event.ActionEvent;
import javafx.event.EventHandler;
import javafx.fxml.FXML;
import javafx.geometry.Insets;
import javafx.scene.Scene;
import javafx.scene.control.Label;
import javafx.scene.image.ImageView;
import javafx.scene.layout.AnchorPane;
import javafx.scene.layout.StackPane;
import javafx.scene.text.Font;
import javafx.stage.Stage;
import model.account.EmployerAccount;
import model.event.WorkEvent;

/**
 * Used in HistoryCurrentPane.fxml
 * 
 * @author NigelChen
 * @version a
 * @since a
 */
public class HistoryCurrentPaneController extends Controller {
	@FXML
	private AnchorPane anchorCurrentPane;
	@FXML
	private Label lbJobName;
	@FXML
	private Label lbManagerName;
	@FXML
	private Label lbHourlyRate;
	@FXML
	private Label lbContact;
	@FXML
	private JFXButton btnCheckTotalPay;
	@FXML
	private JFXButton btnRetire;
	@FXML
	private JFXButton btnChat;
	@FXML
	private JFXButton btnFileTransfer;
	@FXML
    private StackPane stackPane;
    @FXML
    private ImageView imageHolder;
	
	private static JFXDialog dialog;
	
	private WorkEvent work;
	
	// Event Listener on JFXButton[#btnCheckTotalPay].onAction
	@FXML
	public void handleCheckTotalPay(ActionEvent event) {
		CheckTotalPayDialogController.setWorkObj(work);
		JFXDialogLayout content = new JFXDialogLayout();
		
		try {
			content.getChildren().add(m.getScene("/employee/CheckTotalPayDialog.fxml").load());
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		
		dialog = new JFXDialog(stackPane, content, JFXDialog.DialogTransition.RIGHT);
		JFXButton updateAboutMeBtn = new JFXButton();
		updateAboutMeBtn.setOnAction(new EventHandler<ActionEvent>() {
			@Override
			public void handle(ActionEvent event) {
				
				JFXSnackbar snackbar = new JFXSnackbar(stackPane);
					   snackbar.show("Send liaoo", 2000);
						dialog.close();
					}
				});
		
		content.setActions(updateAboutMeBtn);
		dialog.show();
		}
		

	@FXML
	public void handleRetire(ActionEvent event) {
		// TODO Autogenerated
		JobsDAO_Sql data = new JobsDAO_Sql();
		data.transferFromAcceptedToPendingResign(s.getAcc().getLoginEmail(), work.getJobTitle());
		
		Stage s = new Stage();
		s.setTitle("Resignation");
		Label message = new Label("Resign request sent!");
		message.setFont(new Font(20));
		message.setPadding(new Insets(10,20,10,20));
		s.setScene(new Scene(message));
		s.showAndWait();
		
		try {
			m.swapScene("/employee/historyCurrent.fxml");
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}

	@FXML
	public void handleChat(ActionEvent event) {
		ChatController.setW(work);
		try {
			m.swapScene("/employee/Chat.fxml");
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}

	// Event Listener on JFXButton[#btnFileTransfer].onAction
	@FXML
	public void handleFileTransfer(ActionEvent event) {
		try {
			FileTransferController.setWork(work);
			m.swapScene("/employee/FileTransfer.fxml");
		} catch (IOException e) {
			e.printStackTrace();
		}
	}
	
	public void setWorkDetails(WorkEvent work, EmployerAccount employer) {
		this.work = work;
		
		lbJobName.setText(work.getJobTitle());

		String employerContact = new JobsDAO_Sql().getEmployerOfJob(work.getJobTitle()).getLoginEmail();
		lbContact.setText("Email: " + employerContact);
		lbManagerName.setText("Employer: " + employer.getName());
		lbHourlyRate.setText("Rate: $" + work.getWeekdayRate() + "/hr");
	}


	public static JFXDialog getDialog() {
		return dialog;
	}


	public static void setDialog(JFXDialog dialog) {
		HistoryCurrentPaneController.dialog = dialog;
	}
	
	public void initialize() {
		btnRetire.setText("Resign");
		btnRetire.setOnAction(e -> {
			handleRetire(null);
			btnRetire.setDisable(true);
		});
	}
}
