package controller.employee;

import java.io.IOException;

import com.jfoenix.controls.JFXButton;
import com.jfoenix.controls.JFXDrawer;
import com.jfoenix.controls.JFXHamburger;
import com.jfoenix.transitions.hamburger.HamburgerBackArrowBasicTransition;

import application.MyJobLeh;
import controller.Controller;
import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.scene.control.ScrollPane;
import javafx.scene.input.MouseEvent;
import javafx.scene.layout.VBox;
import model.timetable.LegendItem;
import model.timetable.Timetable;

/**
 * 
 * @author WHO WROTE THIS
 * @version final
 * @since a
 */
public class ProfileTimetableController extends Controller {
	
	@FXML
	private ScrollPane ScrollPaneCurrent;
	@FXML
	private VBox timetablePane;
	@FXML
    private JFXDrawer fxDrawer;
    @FXML
    private JFXHamburger fxHamburg;


	public void initialize() {
		Timetable t = new Timetable(600,400);
		timetablePane.getChildren().add(t);
		t.addEventFromList();
		
		//Drawer
		try {
			VBox box = m.getScene("/Drawer.fxml").load();
			fxDrawer.setSidePane(box);
			fxHamburg.addEventHandler(MouseEvent.MOUSE_CLICKED, (e) -> {

				if (fxDrawer.isShown()) {
					fxDrawer.close();
				} else {
					fxDrawer.open();
				}
			});
		} catch (IOException e1) {
			// TODO Auto-generated catch block
			e1.printStackTrace();
		}
	}
	
	// Event Listener on JFXButton[#btnHome].onAction
	@FXML
	public void handleHome(ActionEvent event) {
		// TODO Autogenerated
	}

	// Event Listener on JFXButton[#btnJobs].onAction
	@FXML
	public void handleJobs(ActionEvent event) {
		// TODO Autogenerated
	}

	// Event Listener on JFXButton[#btnHistory].onAction
	@FXML
	public void handleHistory(ActionEvent event) {
		// TODO Autogenerated
	}

	// Event Listener on JFXButton[#btnProfile].onAction
	@FXML
	public void handleProfile(ActionEvent event) {
		// TODO Autogenerated
	}

	// Event Listener on JFXButton[#btnFeedback].onAction
	@FXML
	public void handleFeedBack(ActionEvent event) {
		// TODO Autogenerated
	}

	// Event Listener on JFXButton[#btnLogout].onAction
	@FXML
	public void handleLogout(ActionEvent event) {
		// TODO Autogenerated
	}

	// Event Listener on JFXButton[#btnCurrent].onAction
	@FXML
	public void handleCurrent(ActionEvent event) {
		// TODO Autogenerated
	}

	// Event Listener on JFXButton[#btnPending].onAction
	@FXML
	public void handlePending(ActionEvent event) {
		// TODO Autogenerated
	}

}
